### PR TITLE
Initial stab at traffic action

### PR DESCRIPTION
**Pull request by SimonCW**
This is an initial version to solve: https://github.com/at-gmbh/at-python-template/issues/22. It doesn't save the traffic stats in a separate private repository but in the same repository on a branch called "traffic". I think this is fine, the traffic data doesn't contain sensitive information. It runs once per week on Sundays. 

I haven't work with GH actions before and cannot imagine how to test this without merging :).

### CODE REVIEW

**Comment by sbunzel** [comment]
Thanks Simon! I would like to leave the final review of this to @klamann as I don’t have experience with GH actions.

Two questions:
* Will there be one file per week in the current setup? How will they be called and which data will they contain? I don’t see any specification of the file name in the action specifications.
* Is it possible to trigger this manually on the feature branch for testing?

**Review by sbunzel — COMMENTED** [review]
Would it make sense to call this file `traffic.yml` and give the workflow a name? Compare: https://github.com/at-gmbh/at-python-template/blob/master/.github/workflows/tests-conda.yml#L1

**Comment by klamann** [comment]
we should make a test run to see if this actually works. please add a temporary trigger on this PR like so

```
on:
  pull_request:
    branches: [ feature/save-traffic ]
```

**Comment by klamann** [comment]
[tada!](https://github.com/at-gmbh/at-python-template/tree/traffic) :blush:

**Review by klamann — APPROVED** [review]

**Review by sbunzel — APPROVED** [review]

**Comment by sbunzel** [comment]
LGTM, thanks @klamann! 👍 
@SimonCW, please merge this if you're happy with the result. :)

**Comment by SimonCW** [comment]
Hi @klamann, 

thanks for jumping on this so quickly! The only thing still bothering me is the spacing between the subplots and the messed up year in the x-axis date. However, this is minor and needs to be fixed on the action's repo. I submitted a [PR](https://github.com/sangonzal/repository-traffic-action/pull/9) there. 

Merging ...

**Pull request merged**
