### PR TITLE
Fix/issue28

### LINKED ISSUE #10: Add support for Poetry
I believe it would be great if, as an alternative to pip and conda, this template also supported [poetry](https://python-poetry.org/).

### Advantages
1. Easy project isolation
2. Automatic dependency resolution and reproducible builds
3. Only one config file (pyproject.toml) reduces clutter

### Disadvantages
1. This will increase the complexity of the template
2. It will make the template less opinionated, which makes it less helpful as a tool to bootstrap new python projects

In my opinion, poetry is wholly superior to the traditional approach of pip, setup.py and requirements.txt. Thus, if increasing complexity is a concern, we could try something like:

1. Implement poetry for a specified trial period (e.g. 6 months)
2. At the end of the period, if a few projects have used and liked poetry, remove (or deprecate) the pip option in the template
3. If no projects have used poetry, or people ran into difficulties or disliked it, remove poetry from the template

### Required Work
Here's my assessment of what needs to be done:
1. Add poetry option to `cookiecutter.json`
2. Add `pyproject.toml` template and update `handle_package_manager()` accordingly
3. Create `Dockerfile__poetry` template and update `handle_docker()` posthook accordingly
4. Update `docker-compose.yml` template (behaviour for poetry should be the same as for pip)

Since the editor config files do not point to python executables, there's no need to change them.

I may have missed something; let me know if you notice anything! Thanks 😄

### LINKED ISSUE #28: jupyter dependencies missing for poetry option
The jupyter and ipykernel dependencies are not installed when you choose to work with poetry AND notebooks in the cookiecutter prompts

### PR DESCRIPTION
**Pull request by rauerhans**
pretty self explanatory, Closes #28

### CODE REVIEW

**Comment by rauerhans** [comment]
merged, should be fine

**Comment by alex-mckenzie-sumup** [comment]
Hey - sorry I didn't see this before it was merged, I've been very busy lately! I'd suggest that, instead of using the `jupyter` package, you use `jupyterlab` (which includes jupyter notebook). Alternatively you can use the `notebook` package. Both of these are taken from the [jupyter website](https://jupyter.org/install). [As you can see here](https://pypi.org/project/jupyter/#history), the package `jupyter` hasn't been updated since 2015.

Btw h/t @klamann: I didn't know that the `jupyter` package was out-of-date until he told me :)

**Comment by Arrrlex** [comment]
Hey - sorry I didn't see this before it was merged, I've been very busy lately! I'd suggest that, instead of using the `jupyter` package, you use `jupyterlab` (which includes jupyter notebook). Alternatively you can use the notebook package. Both of these are taken from the [jupyter website](https://jupyter.org/install). [As you can see here](https://pypi.org/project/jupyter/#history), the package `jupyter` hasn't been updated since 2015.

Btw h/t @klamann: I didn't know that the jupyter package was out-of-date until he told me :)

**Comment by rauerhans** [comment]
ha, just when I merged it. I'm not a regular user of jupyter. But I can fix it real quick.

**Comment by rauerhans** [comment]
https://github.com/at-gmbh/at-python-template/pull/32

**Comment by sbunzel** [comment]
This made me want to give poetry a serious try, thanks @Arrrlex and @rauerhans ;)

**Pull request merged**
