### PR TITLE
Add data folder based on cookiecutter-data-science

### PR DESCRIPTION
**Pull request by SimonCW**
Hi, 

I added a data folder and sub-folders based on http://drivendata.github.io/cookiecutter-data-science/#directory-structure. 
I have a split opinion on this one. I think most of the time the data should stay on the cloud infrastructure. However, there are projects where this is not possible ... . 

I thought about making it an option but I think it is easier to just delete the folder if it is not needed.

### CODE REVIEW

**Comment by klamann** [comment]
I like having a data folder and at the same time having it excluded in `.gitignore`, so folks don't accidentally push files from there (unless they use git lfs, but whoever knows about git lfs probably knows their way around gitignore anyways ^^). I'm not sure about the subfolders, personally I never used a structure like this. Maybe just have the `data` folder and `.gitkeep` inside?

**Comment by SimonCW** [comment]
@klamann I have similar feelings because I've mostly used Cloud Storage for all my projects. I like the compromise of only having a data folder without sub-folders and updated accordingly

**Comment by sbunzel** [comment]
Hey @SimonCW, I‘m on board with adding a data folder to the template. Two questions though:
1. Do we want to add some context on the purpose of the folder to the readme (of this repo, not the one we create via the template)? I.e. a pointer to Cookiecutter DS and a hint that we suggest using cloud storage accessible to the whole team if possible?
2. Will the .gitkeep file remain in the folder that is created by Cookiecutter? I feel that this might be confusing for users not familiar with the concept or how this template works, especially since the data folder is in .gitignore (rightfully so).

**Comment by SimonCW** [comment]
@sbunzel, 
1. I would say no, the folder name should be self-explanatory
2. Yep, will remain. There is no way around that and I think everyone should be able to understand it from the file name or google in 30 seconds ;)

**Comment by rauerhans** [comment]
I think this is fine to merge, what are you waiting for?

**Comment by sbunzel** [comment]
> @sbunzel,
> 
> 1. I would say no, the folder name should be self-explanatory
> 2. Yep, will remain. There is no way around that and I think anyone should be able to understand it from the file name or google in 30 seconds ;)

@SimonCW, sorry for the late reply :-) 

1. Okay
2. I find it confusing that the template creates a `data` folder which is listed in `.gitignore` (rightfully so), but contains a `.gitkeep` file. That doesn't make sense to me. I get why we need it to create the data folder in the first place, but I think we should clean it up in our post_gen_project hooks.

**Comment by klamann** [comment]
I agree, the method right now doesn't work as intended, because all contents under `data` are ignored, even the `.gitkeep` file. So when you apply the template, you will have the data folder, but everyone else who clones the git repo won't.

Here's what we should do: ignore the contents of `data` and add an exception to `.gitignore` for `data/.gitkeep`, as explained in [this article](https://medium.com/@kinduff/hey-git-please-keep-those-folders-eb0ed37621c8).

**Pull request merged**
